name: lint

on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: "Vala Lint"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: elementary/actions/vala-lint@master
      with:
        conf: vala-lint.conf
